version: "3.6"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql
    networks:
      - empik-net
  empik-app:
    depends_on:
      - postgres
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    build: ../
    ports:
      - "8888:8888"
    networks:
      - empik-net

networks:
  empik-net:
    driver: bridge

volumes:
  postgres-data:
